/*
 * Material Constants
 * Each action has a corresponding type, which the reducer knows and picks up on.
 * To avoid weird typos between the reducer and the actions, we save them as
 * constants here. We prefix them with 'yourproject/YourComponent' so we avoid
 * reducers accidentally picking up actions they shouldn't.
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'yourproject/YourContainer/YOUR_ACTION_CONSTANT';
 */
export const SHOW_ADD_MATERIAL = "OS/_SHOW_ADD_MATERIAL";
export const HIDE_ADD_MATERIAL = "OS/_HIDE_ADD_MATERIAL";

export const SHOW_DELETE_MATERIAL_MODAL = "OS/_SHOW_DELETE_MATERIAL_MODAL";
export const HIDE_DELETE_MATERIAL_MODAL = "OS/_HIDE_DELETE_MATERIAL_MODAL";

export const SHOW_NEW_MATERIAL_DROPDOWN = "OS/_SHOW_NEW_MATERIAL_DROPDOWN";
export const HIDE_NEW_MATERIAL_DROPDOWN = "OS/_HIDE_NEW_MATERIAL_DROPDOWN";

export const GET_AD_METERIALS_REQUEST = "OS/_GET_AD_METERIALS_REQUEST";
export const GET_AD_METERIALS_SUCCESS = "OS/_GET_AD_METERIALS_SUCCESS";
export const GET_AD_METERIALS_FAILURE = "OS/_GET_AD_METERIALS_FAILURE";

export const GET_IATYPE_BYID_REQUEST = "OS/_GET_IATYPE_BYID_REQUEST_M";
export const GET_IATYPE_BYID_FAILURE = "OS/_GET_IATYPE_BYID_FAILURE_M";
export const GET_IATYPE_BYID_SUCCESS = "OS/_GET_IATYPE_BYID_SUCCESS_M";

export const QUERY_ALL_MODELTYPES_REQUEST = "OS/_QUERY_ALL_MODELTYPES_REQUEST";
export const QUERY_ALL_MODELTYPES_SUCCESS = "OS/_QUERY_ALL_MODELTYPES_SUCCESS";
export const QUERY_ALL_MODELTYPES_FAILURE = "OS/_QUERY_ALL_MODELTYPES_FAILURE";

export const GET_AD_METERIAL_BYID_REQUEST = "OS/_GET_AD_METERIAL_BYID_REQUEST";
export const GET_AD_METERIAL_BYID_SUCCESS = "OS/_GET_AD_METERIAL_BYID_SUCCESS";
export const GET_AD_METERIAL_BYID_FAILURE = "OS/_GET_AD_METERIAL_BYID_FAILURE";

export const ADD_METERIAL_REQUEST = "OS/_ADD_METERIAL_REQUEST";
export const ADD_METERIAL_SUCCESS = "OS/_ADD_METERIAL_SUCCESS";
export const ADD_METERIAL_FAILURE = "OS/_ADD_METERIAL_FAILURE";

export const DELETE_METERIAL_REQUEST = "OS/_DELETE_METERIAL_REQUEST";
export const DELETE_METERIAL_SUCCESS = "OS/_DELETE_METERIAL_SUCCESS";
export const DELETE_METERIAL_FAILURE = "OS/_DELETE_METERIAL_FAILURE";

export const UPDATE_METERIAL_REQUEST = "OS/_UPDATE_METERIAL_REQUEST";
export const UPDATE_METERIAL_SUCCESS = "OS/_UPDATE_METERIAL_SUCCESS";
export const UPDATE_METERIAL_FAILURE = "OS/_UPDATE_METERIAL_FAILURE";

export const ADD_MATERIAL_FILE_REQUEST = "OS/_ADD_MATERIAL_FILE_REQUEST";
export const ADD_MATERIAL_FILE_SUCCESS = "OS/_ADD_MATERIAL_FILE_SUCCESS";
export const ADD_MATERIAL_FILE_FAILURE = "OS/_ADD_MATERIAL_FILE_FAILURE";

export const SAVE_FORM_DATA = "OS/_SAVE_FORM_DATA_M";

export const GET_MATERIAL_INFO_REQUEST = "OS/_GET_MATERIAL_INFO_REQUEST";
export const GET_MATERIAL_INFO_SUCCESS = "OS/_GET_MATERIAL_INFO_SUCCESS";
export const GET_MATERIAL_INFO_FAILURE = "OS/_GET_MATERIAL_INFO_FAILURE";

export const SET_CURRENT_PAGE = "OS/_SET_CURRENT_PAGE";

export const SET_FILE_DATA = "OS/_SET_FILE_DATA";

export const SET_SWITCHER = "OS/_SET_SWITCHER";

export const SET_MATERIAL_SCHEMA = "OS/_SET_MATERIAL_SCHEMA";
